package require

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"io"
	"regexp"
	"sort"
)

var goIdentifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func GenerateGlue(
	w io.Writer,
	packageName, cliImport string,
	mods []ResolvedModule,
) error {
	if w == nil {
		return errors.New("require: nil output")
	}
	if !goIdentifier.MatchString(packageName) {
		return fmt.Errorf("require: invalid package name %q", packageName)
	}
	if cliImport == "" {
		cliImport = "github.com/nexssp/flow/cli"
	}

	sorted := append([]ResolvedModule(nil), mods...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Requirement.Import < sorted[j].Requirement.Import
	})

	var src bytes.Buffer
	fmt.Fprintln(&src, "// Code generated by `nexssflow require`; DO NOT EDIT.")
	fmt.Fprintf(&src, "package %s\n\n", packageName)
	fmt.Fprintln(&src, "import (")
	fmt.Fprintf(&src, "\nnexsscli %q\n", cliImport)
	for i := range sorted {
		mod := &sorted[i]
		if mod.Requirement.Import == "" {
			return errors.New("require: resolved module has empty import path")
		}
		fmt.Fprintf(&src, "\tnexssreq%d %q\n", i, mod.Requirement.Import)
	}
	fmt.Fprintln(&src, ")")
	fmt.Fprintln(&src)
	fmt.Fprintln(&src, "// init registers all @require Bundle's before cli.Run.")
	fmt.Fprintln(&src, "func init() {")
	fmt.Fprintln(&src, "\tnexsscli.RegisterBundle(")
	for i := range sorted {
		mod := &sorted[i]
		fn := mod.Requirement.Options["bundle"]
		if fn == "" {
			fn = "Bundle"
		}
		if !goIdentifier.MatchString(fn) {
			return fmt.Errorf("require: invalid bundle function %q for %s",
				fn, mod.Requirement.Import)
		}
		fmt.Fprintf(&src, "\t\tnexssreq%d.%s(%s),\n",
			i, fn, optionsLiteral(mod.Requirement.Options))
	}
	fmt.Fprintln(&src, "\t)")
	fmt.Fprintln(&src, "}")

	formatted, err := format.Source(src.Bytes())
	if err != nil {
		return fmt.Errorf("require: format generated glue: %w", err)
	}
	_, err = w.Write(formatted)
	return err
}

func optionsLiteral(opts map[string]string) string {
	keys := make([]string, 0, len(opts))
	for k := range opts {
		if k == "bundle" {
			continue
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if len(keys) == 0 {
		return "nil"
	}
	var sb bytes.Buffer
	sb.WriteString("map[string]string{")
	for i, k := range keys {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%q: %q", k, opts[k])
	}
	sb.WriteString("}")
	return sb.String()
}
