package runner

import (
	"bufio"
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/nexssp/flow"
	"github.com/nexssp/kernel/xerr"
)

const harnessMainTmpl = `// Code generated by nexss. DO NOT EDIT.
//
// This harness exists because the flow you ran declares one or more
// @require directives. Each required package must export a function
// ` + "`Library() flow.Library`" + `.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/signal"
	"strings"
	"syscall"

	"github.com/nexssp/flow"
	flowrunner "github.com/nexssp/flow/runner"
{{range .Libs}}
	lib{{.Index}} "{{.Import}}"
{{- end}}
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	libs := []flow.Library{
		flow.StandardLibrary(),
{{- range .Libs}}
		lib{{.Index}}.Library(),
{{- end}}
	}

	reg, err := flow.BuildRegistry(libs...)
	if err != nil {
		fmt.Fprintln(os.Stderr, "❌", err)
		os.Exit(1)
	}

	req := flowrunner.Request{Payload: map[string]any{}}
	for _, arg := range os.Args[1:] {
		switch {
		case strings.HasPrefix(arg, "{"):
			if err := json.Unmarshal([]byte(arg), &req.Payload); err != nil {
				fmt.Fprintln(os.Stderr, "❌ invalid JSON payload:", err)
				os.Exit(1)
			}
		case !strings.HasPrefix(arg, "-") && req.Path == "":
			req.Path = arg
		default:
			req.Args = append(req.Args, arg)
		}
	}
	if req.Path == "" {
		fmt.Fprintln(os.Stderr, "❌ usage: runner <path.flow> [json_payload] [flags]")
		os.Exit(1)
	}
	os.Exit(flowrunner.RunWithRegistry(ctx, req, reg, nil))
}
`

const harnessGoModTmpl = `module nexss-generated-runner

go 1.23
{{if .FlowModuleReplace}}
replace github.com/nexssp/flow => {{.FlowModuleReplace}}
{{end -}}
{{range .Requires}}
require {{.Import}} {{if .Version}}{{.Version}}{{else}}v0.0.0{{end}}
{{- end}}
{{range .Replaces}}
replace {{.Module}} => {{.Dir}}
{{- end}}
`

type harnessLib struct {
	Index  int
	Import string
}

type goModReplace struct {
	Module string
	Dir    string
}

type harnessMainData struct {
	Libs []harnessLib
}

type harnessGoModData struct {
	FlowModuleReplace string
	Requires          []flow.Requirement
	Replaces          []goModReplace
}

func writeHarness(dir string, reqs []flow.Requirement, flowModule string) error {
	libs := make([]harnessLib, len(reqs))
	for i, r := range reqs {
		libs[i] = harnessLib{Index: i, Import: r.Import}
	}

	if err := renderTemplate(
		filepath.Join(dir, "main.go"),
		harnessMainTmpl,
		harnessMainData{Libs: libs},
	); err != nil {
		return err
	}

	replaces, err := collectReplaces(reqs)
	if err != nil {
		return err
	}

	data := harnessGoModData{
		FlowModuleReplace: flowModule,
		Requires:          reqs,
		Replaces:          replaces,
	}

	return renderTemplate(filepath.Join(dir, "go.mod"), harnessGoModTmpl, data)
}

func collectReplaces(reqs []flow.Requirement) ([]goModReplace, error) {
	seen := make(map[string]string, len(reqs))

	var out []goModReplace

	add := func(module, dir string) {
		if module == "" || dir == "" {
			return
		}

		if prev, ok := seen[module]; ok && prev == dir {
			return
		}

		seen[module] = dir
		out = append(out, goModReplace{Module: module, Dir: dir})
	}

	for _, r := range reqs {
		if !r.IsLocal() {
			continue
		}

		add(r.ModulePath, r.ModuleRoot)

		nested, err := readReplaces(filepath.Join(r.ModuleRoot, "go.mod"))
		if err != nil {
			return nil, xerr.Internal(
				"nexss: read replaces from "+r.ModuleRoot, err)
		}

		for _, n := range nested {
			add(n.Module, n.Dir)
		}
	}

	return out, nil
}

func readReplaces(gomodPath string) ([]goModReplace, error) {
	f, err := os.Open(gomodPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}

		return nil, err
	}
	defer f.Close()

	var out []goModReplace

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "replace ") {
			continue
		}

		body := strings.TrimSpace(strings.TrimPrefix(line, "replace "))

		arrow := strings.Index(body, "=>")
		if arrow < 0 {
			continue
		}

		left := strings.TrimSpace(body[:arrow])
		right := strings.TrimSpace(body[arrow+2:])

		if fields := strings.Fields(left); len(fields) > 0 {
			left = fields[0]
		}

		if !looksLikeLocalDir(right) {
			continue
		}

		dir := right
		if !filepath.IsAbs(dir) {
			dir = filepath.Join(filepath.Dir(gomodPath), dir)
		}

		abs, err := filepath.Abs(dir)
		if err != nil {
			continue
		}

		out = append(out, goModReplace{Module: left, Dir: abs})
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return out, nil
}

func looksLikeLocalDir(s string) bool {
	if strings.HasPrefix(s, "./") ||
		strings.HasPrefix(s, "../") ||
		strings.HasPrefix(s, "/") ||
		strings.HasPrefix(s, `.\`) ||
		strings.HasPrefix(s, `..\`) {
		return true
	}

	if len(s) >= 2 && s[1] == ':' {
		return true
	}

	return false
}

func renderTemplate(path, tmpl string, data any) error {
	t, err := template.New(filepath.Base(path)).Parse(tmpl)
	if err != nil {
		return xerr.Internal("nexss: parse template "+path, err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return xerr.Internal("nexss: render "+path, err)
	}

	// 0600: generated harness lives under .nexss/cache/ and should be
	// owner-only even though it carries no secrets.
	return os.WriteFile(path, buf.Bytes(), 0o600)
}
